spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      name: currency-conversion-service
  application:
    name: currency-conversion-service
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/auth/realms/spring-boot-realm/protocol/openid-connect/token/introspect
          client-id: currency-conversion-service
          client-secret: 639232b9-3798-42d2-b3d2-c2c25f87b3f2
server:
  port: 8100
currency-exchange:
  url: http://localhost:8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka